spring:
 mvc:
   view:
     prefix: /pages/
     suffix: .jsp
 datasource:    url: jdbc:mysql://localhost:3306/ParkingSystem
    username: root
    password: akshay
     
home:
 message: Welcome To Metacube Parking System